//Auth
export const AUTH_START = "AUTH_START";
export const AUTH_INIT = "AUTH_INIT";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const UPDATE_EMAIL = "UPDATE_EMAIL";

//Modify account info
export const MODIFY_START = "MODIFY_START";
export const MODIFY_INIT = "MODIFY_INIT";
export const MODIFY_SUCCESS = "MODIFY_SUCCESS";
export const MODIFY_FAIL = "MODIFY_FAIL";

// Project Reducer
export const FETCH_PROJECTS_START = "FETCH_PROJECTS_START";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAIL = "FETCH_PROJECTS_FAIL";
export const SELECT_PROJECT = "SELECT_PROJECT";

// Project Details Reducer
export const FETCH_PROJECT_DETAILS_START = "FETCH_PROJECT_DETAILS_START";
export const FETCH_PROJECT_DETAILS_SUCCESS = "FETCH_PROJECT_DETAILS_SUCCESS";
export const FETCH_PROJECT_DETAILS_FAIL = "FETCH_PROJECT_DETAILS_FAIL";

//Users reducer
export const ADD_USER_START = "ADD_USER_START";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";
// export const REMOVE_USER_SUCCESS = "REMOVE_USER_SUCCESS";
// export const REMOVE_USER_FAIL = "REMOVE_USER_FAIL";
export const FETCH_PROJECT_USERS_START = "FETCH_PROJECT_USERS_START";
export const FETCH_PROJECT_USERS_SUCCESS = "FETCH_PROJECT_USERS_SUCCESS";
export const FETCH_PROJECT_USERS_FAIL = "FETCH_PROJECT_USERS_FAIL";

//Roles reducer
export const CREATE_ROLE_START = "CREATE_ROLE_START";
export const CREATE_ROLE_SUCCESS = "CREATE_ROLE_SUCCESS";
export const CREATE_ROLE_FAIL = "CREATE_ROLE_FAIL";
// export const REMOVE_ROLE_SUCCESS = "REMOVE_ROLE_SUCCESS";
// export const REMOVE_ROLE_FAIL = "REMOVE_ROLE_FAIL";
export const FETCH_PROJECT_ROLES_START = "FETCH_PROJECT_ROLES_START";
export const FETCH_PROJECT_ROLES_SUCCESS = "FETCH_PROJECT_ROLES_SUCCESS";
export const FETCH_PROJECT_ROLES_FAIL = "FETCH_PROJECT_ROLES_FAIL";
export const FETCH_PRIVILEGES_SUCCESS = "FETCH_PROJECT_PRIVILEGES_SUCCESS";

//modify role reducer
export const FETCH_ROLE_PRIVILEGES_START = "FETCH_ROLE_PRIVILEGES_START";
export const FETCH_ROLE_PRIVILEGES_SUCCESS = "FETCH_ROLE_PRIVILEGES_SUCCESS";
export const FETCH_ROLE_PRIVILEGES_FAIL = "FETCH_ROLE_PRIVILEGES_FAIL";

//user roles reducer
export const FETCH_USER_ROLES_START = "FETCH_USER_ROLES_START";
export const FETCH_USER_ROLES_SUCCESS = "FETCH_USER_ROLES_SUCCESS";
export const FETCH_USER_ROLES_FAIL = "FETCH_USER_ROLES_FAIL";

export const FETCH_USER_PRIVILEGES_START = "FETCH_USER_PRIVILEGES_START";
export const FETCH_USER_PRIVILEGES_SUCCESS = "FETCH_USER_PRIVILEGES_SUCCESS";
export const FETCH_USER_PRIVILEGES_FAIL = "FETCH_USER_PRIVILEGES_FAIL";

//artifact types reducer
export const FETCH_ARTIFACT_TYPES_START = "FETCH_ARTIFACT_TYPES_START";
export const FETCH_ARTIFACT_TYPES_SUCCESS = "FETCH_ARTIFACT_TYPES_SUCCESS";
export const FETCH_ARTIFACT_TYPES_FAIL = "FETCH_ARTIFACT_TYPES_FAIL";
export const CREATE_ARTIFACT_TYPE_START = "CREATE_ARTIFACT_TYPE_START";
export const CREATE_ARTIFACT_TYPE_SUCCESS = "CREATE_ARTIFACT_TYPE_SUCCESS";
export const CREATE_ARTIFACT_TYPE_FAIL = "CREATE_ARTIFACT_TYPE_FAIL";

//artifact reducer
export const FETCH_ARTIFACTS_START = "FETCH_ARTIFACTS_START";
export const FETCH_ARTIFACTS_SUCCESS = "FETCH_ARTIFACTS_SUCCESS";
export const FETCH_ARTIFACTS_FAIL = "FETCH_ARTIFACTS_FAIL";
export const CREATE_ARTIFACT_START = "CREATE_ARTIFACT_START";
export const CREATE_ARTIFACT_SUCCESS = "CREATE_ARTIFACT_SUCCESS";
export const CREATE_ARTIFACT_FAIL = "CREATE_ARTIFACT_FAIL";

//traceability link types reducer
export const FETCH_TRACEABILITY_LINK_TYPES_START =
  "FETCH_TRACEABILITY_LINK_TYPES_START";
export const FETCH_TRACEABILITY_LINK_TYPES_SUCCESS =
  "FETCH_TRACEABILITY_LINK_TYPES_SUCCESS";
export const FETCH_TRACEABILITY_LINK_TYPES_FAIL =
  "FETCH_TRACEABILITY_LINK_TYPES_FAIL";
export const CREATE_TRACEABILITY_LINK_TYPE_START =
  "CREATE_TRACEABILITY_LINK_TYPE_START";
export const CREATE_TRACEABILITY_LINK_TYPE_SUCCESS =
  "CREATE_TRACEABILITY_LINK_TYPE_SUCCESS";
export const CREATE_TRACEABILITY_LINK_TYPE_FAIL =
  "CREATE_TRACEABILITY_LINK_TYPE_FAIL";

//traceability link reducer
export const FETCH_TRACEABILITY_LINKS_START = "FETCH_TRACEABILITY_LINKS_START";
export const FETCH_TRACEABILITY_LINKS_SUCCESS =
  "FETCH_TRACEABILITY_LINKS_SUCCESS";
export const FETCH_TRACEABILITY_LINKS_FAIL = "FETCH_TRACEABILITY_LINKS_FAIL";
export const CREATE_TRACEABILITY_LINK_START = "CREATE_TRACEABILITY_LINK_START";
export const CREATE_TRACEABILITY_LINK_SUCCESS =
  "CREATE_TRACEABILITY_LINK_SUCCESS";
export const CREATE_TRACEABILITY_LINK_FAIL = "CREATE_TRACEABILITY_LINK_FAIL";

//change requests reducer
//artifacts
export const FETCH_ARTIFACTS_CHANGE_REQUESTS_START =
  "FETCH_ARTIFACTS_CHANGE_REQUESTS_START";
export const FETCH_ARTIFACTS_CHANGE_REQUESTS_SUCCESS =
  "FETCH_ARTIFACTS_CHANGE_REQUESTS_SUCCESS";
export const FETCH_ARTIFACTS_CHANGE_REQUESTS_FAIL =
  "FETCH_ARTIFACTS_CHANGE_REQUESTS_FAIL";
//traceability links
export const FETCH_TRACEABILITY_LINKS_CHANGE_REQUESTS_START =
  "FETCH_TRACEABILITY_LINKS_CHANGE_REQUESTS_START";
export const FETCH_TRACEABILITY_LINKS_CHANGE_REQUESTS_SUCCESS =
  "FETCH_TRACEABILITY_LINKS_CHANGE_REQUESTS_SUCCESS";
export const FETCH_TRACEABILITY_LINKS_CHANGE_REQUESTS_FAIL =
  "FETCH_TRACEABILITY_LINKS_CHANGE_REQUESTS_FAIL";

//my artifact Change requests reducer
export const FETCH_MY_ARTIFACTS_CHANGE_REQUESTS_START =
  "FETCH_MY_ARTIFACTS_CHANGE_REQUESTS_START";
export const FETCH_MY_ARTIFACTS_CHANGE_REQUESTS_SUCCESS =
  "FETCH_MY_ARTIFACTS_CHANGE_REQUESTS_SUCCESS";
export const FETCH_MY_ARTIFACTS_CHANGE_REQUESTS_FAIL =
  "FETCH_MY_ARTIFACTS_CHANGE_REQUESTS_FAIL";
export const CREATE_ARTIFACT_CHANGE_REQUEST_START =
  "CREATE_ARTIFACT_CHANGE_REQUEST_START";
export const CREATE_ARTIFACT_CHANGE_REQUEST_SUCCESS =
  "CREATE_ARTIFACT_CHANGE_REQUEST_SUCCESS";
export const CREATE_ARTIFACT_CHANGE_REQUEST_FAIL =
  "CREATE_ARTIFACT_CHANGE_REQUEST_FAIL";

//my traceability link Change requests reducer
export const FETCH_MY_TRACEABILITY_LINKS_CHANGE_REQUESTS_START =
  "FETCH_MY_TRACEABILITY_LINKS_CHANGE_REQUESTS_START";
export const FETCH_MY_TRACEABILITY_LINKS_CHANGE_REQUESTS_SUCCESS =
  "FETCH_MY_TRACEABILITY_LINKS_CHANGE_REQUESTS_SUCCESS";
export const FETCH_MY_TRACEABILITY_LINKS_CHANGE_REQUESTS_FAIL =
  "FETCH_MY_TRACEABILITY_LINKS_CHANGE_REQUESTS_FAIL";
export const CREATE_TRACEABILITY_LINK_CHANGE_REQUEST_START =
  "CREATE_TRACEABILITY_LINK_CHANGE_REQUEST_START";
export const CREATE_TRACEABILITY_LINK_CHANGE_REQUEST_SUCCESS =
  "CREATE_TRACEABILITY_LINK_CHANGE_REQUEST_SUCCESS";
export const CREATE_TRACEABILITY_LINK_CHANGE_REQUEST_FAIL =
  "CREATE_TRACEABILITY_LINK_CHANGE_REQUEST_FAIL";

// manager notifications reducer
export const FETCH_NOTIFICATIONS_START = "FETCH_NOTIFICATIONS_START";
export const FETCH_NOTIFICATIONS_SUCCESS = "FETCH_NOTIFICATIONS_SUCCESS";
export const FETCH_NOTIFICATIONS_FAIL = "FETCH_NOTIFICATIONS_FAIL";

// alert reducer
export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
