"""empty message

Revision ID: 02720c792f88
Revises: 4283143ad346
Create Date: 2021-03-07 01:10:27.306767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02720c792f88'
down_revision = '4283143ad346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Artifact_Change_Request_artifact_type_fkey', 'Artifact_Change_Request', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('Artifact_Change_Request_artifact_type_fkey', 'Artifact_Change_Request', 'Artifact_Type', ['artifact_type'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
