"""empty message

Revision ID: 55e746eb7158
Revises: e7245fedd0bc
Create Date: 2021-03-11 02:58:28.262006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e746eb7158'
down_revision = 'e7245fedd0bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Traceability_Link_Change_Request', sa.Column('first_artifact_name', sa.String(), nullable=True))
    op.add_column('Traceability_Link_Change_Request', sa.Column('second_artifact_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Traceability_Link_Change_Request', 'second_artifact_name')
    op.drop_column('Traceability_Link_Change_Request', 'first_artifact_name')
    # ### end Alembic commands ###
