"""empty message

Revision ID: 589b3d1839fc
Revises: 79948563d5cd
Create Date: 2021-02-17 21:59:15.644929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589b3d1839fc'
down_revision = '79948563d5cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Artifact_artifact_type_fkey', 'Artifact', type_='foreignkey')
    op.drop_constraint('Artifact_project_name_fkey', 'Artifact', type_='foreignkey')
    op.create_foreign_key(None, 'Artifact', 'Artifact_Type', ['artifact_type'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Artifact', 'Project', ['project_name'], ['id'], ondelete='CASCADE')
    op.drop_constraint('Artifact_Type_project_name_fkey', 'Artifact_Type', type_='foreignkey')
    op.create_foreign_key(None, 'Artifact_Type', 'Project', ['project_name'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Artifact_Type', type_='foreignkey')
    op.create_foreign_key('Artifact_Type_project_name_fkey', 'Artifact_Type', 'Project', ['project_name'], ['id'])
    op.drop_constraint(None, 'Artifact', type_='foreignkey')
    op.drop_constraint(None, 'Artifact', type_='foreignkey')
    op.create_foreign_key('Artifact_project_name_fkey', 'Artifact', 'Project', ['project_name'], ['id'])
    op.create_foreign_key('Artifact_artifact_type_fkey', 'Artifact', 'Artifact_Type', ['artifact_type'], ['id'])
    # ### end Alembic commands ###
