"""empty message

Revision ID: 5bc19862169f
Revises: ca06ef4fbe31
Create Date: 2021-02-16 00:04:25.058227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc19862169f'
down_revision = 'ca06ef4fbe31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artifact', sa.Column('name', sa.String(), nullable=True))
    op.add_column('roles_privileges', sa.Column('artifact_type', sa.String(), nullable=True))
    op.create_foreign_key(None, 'roles_privileges', 'Artifact_Type', ['artifact_type'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles_privileges', type_='foreignkey')
    op.drop_column('roles_privileges', 'artifact_type')
    op.drop_column('Artifact', 'name')
    # ### end Alembic commands ###
