"""empty message

Revision ID: 68dd1730088d
Revises: 589b3d1839fc
Create Date: 2021-02-26 17:08:44.488401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68dd1730088d'
down_revision = '589b3d1839fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Traceability_Link_Type',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('first_artifact_type', sa.String(), nullable=False),
    sa.Column('second_artifact_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['first_artifact_type'], ['Artifact_Type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_name'], ['Project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['second_artifact_type'], ['Artifact_Type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Traceability_Link_Type')
    # ### end Alembic commands ###
