"""empty message

Revision ID: 6f7d3f681905
Revises: 6822ee96acc7
Create Date: 2021-03-30 17:41:51.743538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f7d3f681905'
down_revision = '6822ee96acc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artifact', sa.Column('modification_date', sa.DateTime(), nullable=True))
    op.add_column('Artifact', sa.Column('modified_by', sa.String(), nullable=True))
    op.add_column('Traceability_Link', sa.Column('modification_date', sa.DateTime(), nullable=True))
    op.add_column('Traceability_Link', sa.Column('modified_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Traceability_Link', 'modified_by')
    op.drop_column('Traceability_Link', 'modification_date')
    op.drop_column('Artifact', 'modified_by')
    op.drop_column('Artifact', 'modification_date')
    # ### end Alembic commands ###
