"""empty message

Revision ID: 79948563d5cd
Revises: 5bc19862169f
Create Date: 2021-02-17 21:57:41.275226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79948563d5cd'
down_revision = '5bc19862169f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Project_manager_fkey', 'Project', type_='foreignkey')
    op.create_foreign_key(None, 'Project', 'User', ['manager'], ['username'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Project', type_='foreignkey')
    op.create_foreign_key('Project_manager_fkey', 'Project', 'User', ['manager'], ['username'])
    # ### end Alembic commands ###
