"""empty message

Revision ID: ca06ef4fbe31
Revises: 67d2152b2f2b
Create Date: 2021-02-12 01:16:52.094438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca06ef4fbe31'
down_revision = '67d2152b2f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Project', sa.Column('manager', sa.String(), nullable=True))
    op.create_foreign_key(None, 'Project', 'User', ['manager'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'Project', type_='foreignkey')
    op.drop_column('Project', 'manager')
    # ### end Alembic commands ###
