"""empty message

Revision ID: e7245fedd0bc
Revises: 02720c792f88
Create Date: 2021-03-07 01:13:04.623581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7245fedd0bc'
down_revision = '02720c792f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Traceability_Link_Change_Request',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reject_reason', sa.String(), nullable=True),
    sa.Column('traceability_link_id', sa.String(), nullable=True),
    sa.Column('traceability_link_name', sa.String(), nullable=False),
    sa.Column('traceability_link_description', sa.String(), nullable=False),
    sa.Column('traceability_link_type', sa.String(), nullable=False),
    sa.Column('first_artifact', sa.String(), nullable=False),
    sa.Column('second_artifact', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['User.username'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_name'], ['Project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Traceability_Link_Change_Request')
    # ### end Alembic commands ###
