"""empty message

Revision ID: f0eb1e5def9d
Revises: fd422ed51d1e
Create Date: 2021-03-05 14:20:10.093008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0eb1e5def9d'
down_revision = 'fd422ed51d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Artifact_Change_Request',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('artifact_id', sa.String(), nullable=True),
    sa.Column('artifact_name', sa.String(), nullable=False),
    sa.Column('artifact_description', sa.String(), nullable=False),
    sa.Column('artifact_type', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_type'], ['Artifact_Type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['User.username'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_name'], ['Project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Artifact_Change_Request')
    # ### end Alembic commands ###
