"""empty message

Revision ID: fd422ed51d1e
Revises: d7d22f9c6ac1
Create Date: 2021-03-02 15:50:10.966725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd422ed51d1e'
down_revision = 'd7d22f9c6ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Artifact_created_by_fkey', 'Artifact', type_='foreignkey')
    op.create_foreign_key(None, 'Artifact', 'User', ['created_by'], ['username'], ondelete='CASCADE')
    op.drop_constraint('Traceability_Link_created_by_fkey', 'Traceability_Link', type_='foreignkey')
    op.create_foreign_key(None, 'Traceability_Link', 'User', ['created_by'], ['username'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Traceability_Link', type_='foreignkey')
    op.create_foreign_key('Traceability_Link_created_by_fkey', 'Traceability_Link', 'User', ['created_by'], ['username'])
    op.drop_constraint(None, 'Artifact', type_='foreignkey')
    op.create_foreign_key('Artifact_created_by_fkey', 'Artifact', 'User', ['created_by'], ['username'])
    # ### end Alembic commands ###
